# Site settings
title: Katrina's Profile
email: katrina.prather@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Katrina's portfolio - learn a little bit about me
baseurl: "/patchwork-gh-pages-24"
url: "https://katrinaprather.github.io"
twitter_username: irock1908
github_username:  katrinaprather
permalink: /blog/:year/:title/


# Build settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM

collections:
    - index
